# 自动构建（避免编译异常，仅在 staging 分支构建，需手动合并）
name: Automatically Build GitBook
on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Compile
      run: |-
        ./build.sh

    # 如果不希望污染 commit 记录，user.email 和 user.name 随便填即可
    # Github Runner 是有权限提交到仓库的，只要 user 不是 owner ，当次 commit 不会被记录
    - name: Commit and push Github page (if changed)
      run: |-
        git diff
        git config --global user.email "github-bot@example.com"
        git config --global user.name "Github-Bot"
        git add -A
        git commit -m "Updated by Github Bot" || exit 0
        git push origin staging

